const QUESTIONS = [
{id: "Q1", niveau: 3, oi: "Établir des faits", competence: "Lire l'organisation du territoire", periodes: ["Les Iroquoiens vers 1500"], points: 1, soustag: "Établir 1 fait - 1", aspects: [{aspect: "Territoire"}], enonce: "Nomme le mode de vie des Iroquoiens vers 1500.", updatedAt: "2026-07-23T13:02:04.859Z"},
{id: "Q2", niveau: 3, oi: "Établir des faits", competence: "Lire l'organisation du territoire", periodes: ["Les Algonquiens vers 1500"], points: 1, soustag: "Établir 1 fait - 1", aspects: [{aspect: "Territoire"}], enonce: "Nomme le mode de vie des Algonquiens vers 1500.", updatedAt: "2026-07-23T13:11:07.174Z"},
{id: "Q3", niveau: 3, oi: "Établir des faits", competence: "Lire l'organisation du territoire", periodes: ["Les Iroquoiens vers 1500"], points: 1, soustag: "Établir 1 fait - 1", aspects: [{aspect: "Activités économiques"}], enonce: "Nomme une activité que les Iroquoiens pratiquent pour se nourrir.", updatedAt: "2026-07-23T13:15:00.179Z"},
{id: "Q4", niveau: 3, oi: "Établir des faits", competence: "Lire l'organisation du territoire", periodes: ["Les Algonquiens vers 1500"], points: 2, soustag: "Établir tous les faits - 2", aspects: [{aspect: "Activités économiques"}], enonce: "Nomme deux activités que les Algonquiens pratiquent pour se nourrir.", updatedAt: "2026-07-23T13:16:21.725Z"},
{id: "Q5", niveau: 3, oi: "Caractériser un territoire", competence: "Lire l'organisation du territoire", periodes: ["Les Iroquoiens vers 1500"], points: 2, soustag: "Caractériser un territoire - 2", aspects: [{aspect: "Territoire"}], enonce: "Nomme deux caractéristiques du village iroquoien qui montrent que les Iroquoiens sont sédentaires.", updatedAt: "2026-07-23T14:05:03.263Z"},
{id: "Q6", niveau: 3, oi: "Caractériser un territoire", competence: "Lire l'organisation du territoire", periodes: ["Les Algonquiens vers 1500"], points: 2, soustag: "Caractériser un territoire - 2", aspects: [{aspect: "Territoire"}], enonce: "Nomme deux caractéristiques du village algonquien qui montrent que les Algonquiens sont nomades.", updatedAt: "2026-07-23T14:12:04.711Z"},
{id: "Q7", niveau: 3, oi: "Établir des faits", competence: "Lire l'organisation du territoire", periodes: ["Les Iroquoiens vers 1500"], points: 2, soustag: "Établir 1 fait - 1", aspects: [{aspect: "Activités économiques"}], enonce: "Nomme deux aliments que les Iroquoiens cultivent pour se nourrir.", updatedAt: "2026-07-23T14:19:19.016Z"}
]
