const REGLETTES = {
"Q1": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q2": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q3": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q4": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit les faits. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q5": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q6": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q7": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit les faits. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q8": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q9": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q10": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q11": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q12": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q13": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q14": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q15": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q16": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q17": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q18": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q19": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q20": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q21": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q22": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q23": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q24": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q25": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q26": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q27": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit les faits. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q28": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q29": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q30": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q31": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q32": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q33": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q34": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q35": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (3 sur 3)"}, {pts: 1, desc: "L'élève met en relation les faits. (2 sur 3)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 3)"}]},
"Q36": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (3 sur 3)"}, {pts: 1, desc: "L'élève met en relation les faits. (2 sur 3)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 3)"}]},
"Q37": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q38": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q39": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q40": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q41": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q42": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q43": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q44": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q45": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q46": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q47": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q48": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]}
}

const IMAGE_DB = {
"campement_algonquien_1.jpg": {src: "images/campement_algonquien_1.jpg", w: 1200, h: 800},
"village_iroquoien_1500_2.jpg": {src: "images/village_iroquoien_1500_2.jpg", w: 1200, h: 800},
"village_iroquoien_1500_1.jpg": {src: "images/village_iroquoien_1500_1.jpg", w: 1200, h: 800},
"campement_algonquien_2.jpg": {src: "images/campement_algonquien_2.jpg", w: 1200, h: 755},
"iroquoiens_recoltes.jpg": {src: "images/iroquoiens_recoltes.jpg", w: 1200, h: 841},
"algonquiens_deplacements_1.jpg": {src: "images/algonquiens_deplacements_1.jpg", w: 1200, h: 783},
"algonquiens_deplacements_2.jpg": {src: "images/algonquiens_deplacements_2.jpg", w: 1200, h: 746},
"algonquiens_deplacements.jpg": {src: "images/algonquiens_deplacements.jpg"},
"autochtones_canot.jpg": {src: "images/autochtones_canot.jpg", w: 1200, h: 801},
"autochtones_troc.jpg": {src: "images/autochtones_troc.jpg", w: 1200, h: 801},
"ressources_mais.jpg": {src: "images/ressources_mais.jpg", w: 1200, h: 960},
"ressources_haricots_courges.jpg": {src: "images/ressources_haricots_courges.jpg", w: 1200, h: 960},
"ressources_fourrures.jpg": {src: "images/ressources_fourrures.jpg", w: 1200, h: 960},
"ressources_viandes_sechees.jpg": {src: "images/ressources_viandes_sechees.jpg", w: 1200, h: 960},
"chaman_animisme.jpg": {src: "images/chaman_animisme.jpg"},
"chaman_ceremonie_1.jpg": {src: "images/chaman_ceremonie_1.jpg", w: 1200, h: 800},
"chaman_ceremonie_2.jpg": {src: "images/chaman_ceremonie_2.jpg", w: 1200, h: 800},
"chaman_ceremonie_3.jpg": {src: "images/chaman_ceremonie_3.jpg", w: 1200, h: 800},
"iroquoien_paniers.jpg": {src: "images/iroquoien_paniers.jpg", w: 1200, h: 800},
"iroquoiens_poterie.jpg": {src: "images/iroquoiens_poterie.jpg", w: 1200, h: 800},
"paniers_tisses.jpg": {src: "images/paniers_tisses.jpg", w: 1200, h: 800},
"poterie.jpg": {src: "images/poterie.jpg", w: 1200, h: 800},
"poterie_vannerie.jpg": {src: "images/poterie_vannerie.jpg", w: 1200, h: 800},
"poterie_cuisson.jpg": {src: "images/poterie_cuisson.jpg", w: 1200, h: 960},
"ressources_poterie_vannerie.jpg": {src: "images/ressources_poterie_vannerie.jpg", w: 1200, h: 800},
"confection_vetements.jpg": {src: "images/confection_vetements.jpg", w: 1200, h: 960},
"raquettes.jpg": {src: "images/raquettes.jpg", w: 1200, h: 800},
"mocassins.jpg": {src: "images/mocassins.jpg", w: 1200, h: 800},
"mocassins_deplacements.jpg": {src: "images/mocassins_deplacements.jpg"},
"agriculture.jpg": {src: "images/agriculture.jpg"},
"cueillette.jpg": {src: "images/cueillette.jpg"},
"peche.jpg": {src: "images/peche.jpg"},
"territoire_iroquoien_1.jpg": {src: "images/territoire_iroquoien_1.jpg", w: 1200, h: 800},
"territoire_iroquoien_2.jpg": {src: "images/territoire_iroquoien_2.jpg"},
"tradition_orale_1.jpg": {src: "images/tradition_orale_1.jpg", w: 1200, h: 800},
"vetements.jpg": {src: "images/vetements.jpg"},
"tradition_orale_4.jpg": {src: "images/tradition_orale_4.jpg", w: 1200, h: 800},
"crosse.jpg": {src: "images/crosse.jpg", w: 1200, h: 800},
"chasse.jpg": {src: "images/chasse.jpg"},
"fetes_communautes_1.jpg": {src: "images/fetes_communautes_1.jpg", w: 1200, h: 800},
"fetes_communautes_2.jpg": {src: "images/fetes_communautes_2.jpg", w: 1200, h: 800}
}

const QUESTIONS = [
{
 id: "Q1",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le mode de vie des Iroquoiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_1500_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les Iroquoiens sont sédentaires.",
 updatedAt: "2026-07-23T20:05:02.100Z"
},
{
 id: "Q2",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le mode de vie des Algonquiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "campement_algonquien_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les Algonquiens sont nomades.",
 updatedAt: "2026-07-23T13:11:07.174Z"
},
{
 id: "Q3",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme une activité que les Iroquoiens pratiquent pour se nourrir.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_1500_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les Iroquoiens pratiquent l'agriculture.\nL'agriculture.",
 updatedAt: "2026-07-23T13:15:00.179Z"
},
{
 id: "Q4",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "Nomme deux activités que les Algonquiens pratiquent pour se nourrir.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "campement_algonquien_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "La chasse.\nLa pêche.\nLa cueillette.",
 updatedAt: "2026-07-23T14:19:58.371Z"
},
{
 id: "Q5",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du village iroquoien qui montrent que les Iroquoiens sont sédentaires.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_1500_2.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les maisons longues.\nLa palissade.\nLes champs de maïs (ou les champs cultivés).\nLe village permanent.",
 updatedAt: "2026-07-23T14:05:03.263Z"
},
{
 id: "Q6",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du village algonquien qui montrent que les Algonquiens sont nomades.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "campement_algonquien_2.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les tipis et les wigwams (des habitations faciles à démonter et à transporter).\nL'absence de champs cultivés.\nLe campement temporaire.\nLes toboggans utilisés pour transporter les biens.\nLes raquettes qui facilitent les déplacements réguliers en hiver.",
 updatedAt: "2026-07-23T14:12:04.711Z"
},
{
 id: "Q7",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme deux aliments que les Iroquoiens cultivent pour se nourrir.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_recoltes.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "Le maïs.\nLes courges.\nLes haricots.",
 updatedAt: "2026-07-23T14:19:19.016Z"
},
{
 id: "Q8",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme un objet utilisé par les peuples autochtones pour se déplacer en hiver.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_deplacements_1.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les raquettes.\nLe toboggan.",
 updatedAt: "2026-07-23T16:18:32.829Z"
},
{
 id: "Q9",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Algonquiens se déplacent au fil des saisons.",
 aspects: [{aspect: "Activités économiques"}, {aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_deplacements_2.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Algonquiens se déplacent pour trouver la nourriture dont ils ont besoin selon les saisons.",
 updatedAt: "2026-07-24T03:55:48.018Z"
},
{
 id: "Q10",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones utilisent un toboggan en hiver.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_deplacements_1.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones utilisent un toboggan pour transporter leurs biens lorsqu'ils se déplacent l'hiver.",
 updatedAt: "2026-07-24T03:56:00.650Z"
},
{
 id: "Q11",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens peuvent vivre au même endroit toute l'année.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_1500_2.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens peuvent vivre au même endroit toute l'année parce qu'ils cultivent du maïs, des haricots et des courges pour se nourrir.",
 updatedAt: "2026-07-24T03:58:10.287Z"
},
{
 id: "Q12",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme un moyen de transport utilisé par les peuples autochtones pour se déplacer sur les cours d'eau.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_canot.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le canot d'écorce.",
 updatedAt: "2026-07-23T16:25:49.573Z"
},
{
 id: "Q13",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones pratiquent le troc.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_troc.jpg", source: "Rreconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones pratiquent le troc pour obtenir des ressources qu'ils ne possèdent pas ou pour répondre à leurs besoins.",
 updatedAt: "2026-07-24T03:58:19.949Z"
},
{
 id: "Q14",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la façon utilisée par les peuples autochtones pour échanger des ressources.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_troc.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le troc.",
 updatedAt: "2026-07-23T16:39:42.480Z"
},
{
 id: "Q15",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent différentes ressources échangées par les nations iroquoiennes vers 1500. Associez chaque document à l'endroit correspondant.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "ressources_mais.jpg", soustitre: "Épis de maïs", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "ressources_fourrures.jpg", soustitre: "Fourrures et peaux d'animaux", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "ressources_viandes_sechees.jpg", soustitre: "Viandes séchées", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "ressources_haricots_courges.jpg", soustitre: "Courges et haricots", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Ressources produites", "Ressources recherchées"], double: true},
 guide: {type: "grille", entetes: ["Ressources produites", "Ressources recherchées"], rangees: [["A et D", "B et C"]]},
 updatedAt: "2026-07-23T16:51:38.199Z"
},
{
 id: "Q16",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent différentes ressources échangées par les nations algonquiennes vers 1500. Associez chaque document à l'endroit correspondant.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "ressources_mais.jpg", soustitre: "Épis de maïs", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "ressources_fourrures.jpg", soustitre: "Fourrures et peaux d'animaux", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "ressources_viandes_sechees.jpg", soustitre: "Viandes séchées", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "ressources_haricots_courges.jpg", soustitre: "Courges et haricots", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Ressources produites", "Ressources recherchées"], double: true},
 guide: {type: "grille", entetes: ["Ressources produites", "Ressources recherchées"], rangees: [["B et C", "A et D"]]},
 updatedAt: "2026-07-23T16:51:26.467Z"
},
{
 id: "Q17",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la personne qui dirige les cérémonies chez les peuples autochtones vers 1500.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "chaman_animisme.jpg", source: "Rreconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le chaman.",
 updatedAt: "2026-07-23T18:16:12.452Z"
},
{
 id: "Q18",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones organisent des cérémonies vers 1500.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "chaman_ceremonie_1.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones participent aux cérémonies pour remercier les esprits de la nature ou demander leur aide ou pratiquer leur religion.",
 updatedAt: "2026-07-24T03:58:40.665Z"
},
{
 id: "Q19",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones respectent la nature vers 1500.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "chaman_ceremonie_2.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones respectent la nature, car ils croient que des esprits vivent dans les animaux, les plantes, les rivières et les montagnes.",
 updatedAt: "2026-07-24T03:58:57.004Z"
},
{
 id: "Q20",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la croyance religieuse pratiquée par les peuples autochtones vers 1500.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "chaman_ceremonie_3.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les peuples autochtones pratiquent l'animisme.",
 updatedAt: "2026-07-23T18:30:34.226Z"
},
{
 id: "Q21",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens utilisent des ressources de la nature pour fabriquer leurs objets.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "ressources_poterie_vannerie.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens utilisent des ressources de la nature pour fabriquer leurs objets parce qu'ils trouvent les plantes ou les fibres végétales ou l'argile dont ils ont besoin dans leur environnement ou dans la nature.",
 updatedAt: "2026-07-24T03:59:10.214Z"
},
{
 id: "Q22",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité représentée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoien_paniers.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La vannerie.\nLe tressage de paniers.",
 updatedAt: "2026-07-23T18:53:47.974Z"
},
{
 id: "Q23",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens fabriquent des paniers.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "paniers_tisses.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens fabriquent des paniers pour transporter, conserver et ranger leurs récoltes et d'autres ressources.",
 updatedAt: "2026-07-24T04:02:08.986Z"
},
{
 id: "Q24",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité représentée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_poterie.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La poterie.",
 updatedAt: "2026-07-23T18:56:47.904Z"
},
{
 id: "Q25",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens fabriquent des pots en terre cuite.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_cuisson.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens fabriquent des pots en terre cuite pour faire cuire ou conserver ou transporter leurs aliments.",
 updatedAt: "2026-07-24T03:59:26.220Z"
},
{
 id: "Q26",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens fabriquent eux-mêmes leurs objets.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_vannerie.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens fabriquent eux-mêmes leurs objets pour répondre à leurs besoins en utilisant les ressources de la nature.",
 updatedAt: "2026-07-24T04:00:03.356Z"
},
{
 id: "Q27",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "Nomme deux objets fabriqués par les Iroquoiens pour conserver leurs récoltes.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_vannerie.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "Un panier tissé.\nUn pot en terre cuite.",
 updatedAt: "2026-07-23T19:29:26.287Z"
},
{
 id: "Q28",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme une ressource utilisée pour fabriquer des paniers tissés.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "ressources_poterie_vannerie.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les fibres végétales.\nLes roseaux.\nL'écorce.",
 updatedAt: "2026-07-23T19:45:09.465Z"
},
{
 id: "Q29",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme une ressource utilisée par les Iroquoiens pour fabriquer des pots en terre cuite.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "ressources_poterie_vannerie.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "L'argile.\nLa terre.",
 updatedAt: "2026-07-23T19:44:52.264Z"
},
{
 id: "Q30",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme une ressource utilisée par les peuples autochtones pour fabriquer leurs vêtements.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "ressources_fourrures.jpg", soustitre: "Fourrures et peaux d'animaux", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les peaux d'animaux.\nLes fourrures.",
 updatedAt: "2026-07-23T19:48:44.259Z"
},
{
 id: "Q31",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones utilisent les peaux d'animaux pour fabriquer leurs vêtements.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "confection_vetements.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones utilisent les peaux d'animaux parce qu'elles sont chaudes ou résistantes ou les protègent du froid.",
 updatedAt: "2026-07-24T04:00:14.874Z"
},
{
 id: "Q32",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones utilisent des raquettes en hiver.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "raquettes.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones utilisent des raquettes pour marcher sur la neige sans s'enfoncer.",
 updatedAt: "2026-07-24T04:02:21.935Z"
},
{
 id: "Q33",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'objet fabriqué.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "mocassins.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Des mocassins.",
 updatedAt: "2026-07-23T19:56:44.164Z"
},
{
 id: "Q34",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones portent des mocassins.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "mocassins_deplacements.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones fabriquent des mocassins pour protéger leurs pieds lorsqu'ils se déplacent.",
 updatedAt: "2026-07-24T04:00:27.458Z"
},
{
 id: "Q35",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 3",
 enonce: "Les documents A à C présentent différentes activités pratiquées par les Iroquoiens vers 1500. Associe chaque document à l'activité correspondante.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "iroquoien_paniers.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "iroquoiens_poterie.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "agriculture.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Agriculture", "Poterie", "Vannerie"]},
 guide: {type: "grille", entetes: ["Agriculture", "Poterie", "Vannerie"], rangees: [["C", "B", "A"]]},
 updatedAt: "2026-07-24T00:49:33.303Z"
},
{
 id: "Q36",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 3",
 enonce: "Les documents A à C présentent différentes activités pratiquées par les Iroquoiens vers 1500. Associe chaque document à l'activité correspondante.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "cueillette.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "peche.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "agriculture.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Agriculture", "Cueillette", "Pêche"]},
 guide: {type: "grille", entetes: ["Agriculture", "Cueillette", "Pêche"], rangees: [["C", "A", "B"]]},
 updatedAt: "2026-07-24T00:53:47.055Z"
},
{
 id: "Q37",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du territoire des Iroquoiens.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_iroquoien_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "Des terres fertiles.\nDes forêts de feuillus.\nDes rivières.\nDes lacs.\nLe fleuve Saint-Laurent.",
 updatedAt: "2026-07-24T00:59:57.204Z"
},
{
 id: "Q38",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les Iroquoiens installent leur village près cours d'eau.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_iroquoien_2.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens s'installent près des rivières et des lacs pour avoir accès à l'eau, à la pêche et pour se déplacer en canot.",
 updatedAt: "2026-07-24T04:00:59.850Z"
},
{
 id: "Q39",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les mères de clan jouent un rôle important chez les Iroquoiens.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "tradition_orale_1.jpg", source: "Adapté de Récitus et reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les mères de clan jouent un rôle important chez les Iroquoiens parce qu'elles choisissent les chefs et participent aux décisions importantes de la communauté.",
 updatedAt: "2026-07-24T04:07:43.551Z"
},
{
 id: "Q40",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme un matériau utilisé pour décorer les vêtements des peuples autochtones vers 1500.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vetements.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Ils décorent leurs vêtements avec des piquants de porc-épic.\nIls décorent leurs vêtements avec des coquillages.\nIls décorent leurs vêtements avec des perles.",
 updatedAt: "2026-07-24T12:21:44.435Z"
},
{
 id: "Q41",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les récits oraux occupent une place importante dans la communauté.",
 aspects: [{aspect: "Culture"}, {aspect: "Communication"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "tradition_orale_4.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les aînés racontent des légendes et des récits (les récits oraux).\nCes récits transmettent les traditions et les enseignements de la communauté (la transmission des connaissances).\nLes jeunes apprennent ainsi les valeurs et l'histoire de leur peuple (la préservation des traditions).",
 updatedAt: "2026-07-24T12:26:56.882Z"
},
{
 id: "Q42",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité pratiquée.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "crosse.jpg", source: "econstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La crosse.",
 updatedAt: "2026-07-24T12:31:19.004Z"
},
{
 id: "Q43",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité pratiquée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "agriculture.jpg", source: "econstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "L'agriculture.",
 updatedAt: "2026-07-24T12:31:54.614Z"
},
{
 id: "Q44",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité pratiquée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "cueillette.jpg", source: "econstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La cueillette.",
 updatedAt: "2026-07-24T12:32:16.888Z"
},
{
 id: "Q45",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité pratiquée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "chasse.jpg", source: "econstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La chasse.",
 updatedAt: "2026-07-24T12:32:43.753Z"
},
{
 id: "Q46",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À partir du document A, nomme l'activité pratiquée.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "peche.jpg", source: "econstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La pêche.",
 updatedAt: "2026-07-24T12:33:06.394Z"
},
{
 id: "Q47",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les rassemblements communautaires sont importants chez les Iroquoiens vers 1500.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "fetes_communautes_1.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les membres de la communauté se réunissent lors de fêtes saisonnières ou de cérémonies (les rassemblements communautaires). \nIls y partagent des repas, des jeux, des chants et des danses (les activités communautaires).\nCes rencontres renforcent les liens entre les membres de la communauté et permettent de transmettre les traditions (la cohésion et la transmission de la culture).",
 updatedAt: "2026-07-24T12:40:16.729Z"
},
{
 id: "Q48",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les rassemblements communautaires sont importants chez les Algonquiens vers 1500.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "fetes_communautes_2.jpg", source: "Reconstitution historique à des fins pédagogiques réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les familles se réunissent lors de fêtes saisonnières ou de rencontres entre bandes (les rassemblements communautaires).\nElles partagent des repas, des jeux, des chants et des danses (les activités communautaires).\nCes rassemblements renforcent les liens entre les membres de la communauté et favorisent l'entraide (la cohésion de la communauté).",
 updatedAt: "2026-07-24T12:41:38.128Z"
}
]
