const REGLETTES = {
"Q1": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q2": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q3": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit un fait. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q4": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q5": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q6": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q7": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q8": {oi: "Caractériser un territoire", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève indique deux caractéristiques."}, {pts: 1, desc: "L'élève indique une caractéristique."}, {pts: 0, desc: "L'élève n'indique pas de caractéristique."}]},
"Q9": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit un fait. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q10": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit un fait. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q11": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q12": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q13": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q14": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q15": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q16": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q17": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q18": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q19": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q20": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q21": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q22": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q23": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q24": {oi: "Établir des comparaisons", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit la différence."}, {pts: 1, desc: "L'élève établit plus ou moins la différence."}, {pts: 0, desc: "L'élève n'établit pas la différence."}]},
"Q25": {oi: "Situer dans l'espace", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève situe le fait dans l'espace."}, {pts: 0, desc: "L'élève ne situe pas le fait dans l'espace."}]},
"Q26": {oi: "Situer dans l'espace", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève situe le fait dans l'espace."}, {pts: 0, desc: "L'élève ne situe pas le fait dans l'espace."}]},
"Q27": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q28": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q29": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q30": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q31": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q32": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q33": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q34": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q35": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q36": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q37": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q38": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q39": {oi: "Établir des liens de causalité", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit correctement le lien de causalité."}, {pts: 1, desc: "L'élève établit partiellement le lien de causalité."}, {pts: 0, desc: "L'élève n'établit pas le lien de causalité."}]},
"Q40": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q41": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q42": {oi: "Mettre en relation des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (4 sur 4)"}, {pts: 1, desc: "L'élève met en relation les faits. (3 ou 2 sur 4)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 4)"}]},
"Q43": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q44": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q45": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q46": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q47": {oi: "Établir des faits", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit tous les faits. (2 sur 2)"}, {pts: 1, desc: "L'élève établit un fait. (1 sur 2)"}, {pts: 0, desc: "L'élève n'établit pas les faits. (0 sur 2)"}]},
"Q48": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q49": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q50": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q51": {oi: "Établir des comparaisons", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit la différence."}, {pts: 1, desc: "L'élève établit plus ou moins la différence."}, {pts: 0, desc: "L'élève n'établit pas la différence."}]},
"Q52": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q53": {oi: "Établir des comparaisons", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit la différence."}, {pts: 1, desc: "L'élève établit plus ou moins la différence."}, {pts: 0, desc: "L'élève n'établit pas la différence."}]},
"Q54": {oi: "Établir des comparaisons", colonnes: ["2 points", "1 point", "0 point"], niveaux: [{pts: 2, desc: "L'élève établit la différence."}, {pts: 1, desc: "L'élève établit plus ou moins la différence."}, {pts: 0, desc: "L'élève n'établit pas la différence."}]},
"Q55": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q56": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q57": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q58": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q59": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q60": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q61": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q62": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]},
"Q63": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q64": {oi: "Établir des faits", colonnes: ["1 point", "0 point"], niveaux: [{pts: 1, desc: "L'élève établit les faits."}, {pts: 0, desc: "L'élève n'établit pas les faits."}]},
"Q65": {oi: "Mettre en relation des faits", colonnes: ["2 points", "0 point"], niveaux: [{pts: 2, desc: "L'élève met en relation tous les faits. (2 sur 2)"}, {pts: 0, desc: "L'élève ne met pas suffisamment en relation les faits. (1 ou 0 sur 2)"}]}
}

const IMAGE_DB = {
"activites_economiques_iroquoiens.jpg": {src: "images/activites_economiques_iroquoiens.jpg", w: 1200, h: 800},
"activites_economiques_algonquiens.jpg": {src: "images/activites_economiques_algonquiens.jpg", w: 1200, h: 841},
"territoire_algonquien_1.jpg": {src: "images/territoire_algonquien_1.jpg", w: 1200, h: 960},
"campement_algonquien_4.jpg": {src: "images/campement_algonquien_4.jpg", w: 1200, h: 900},
"territoire_algonquiens_1.jpg": {src: "images/territoire_algonquiens_1.jpg"},
"territoire_iroquoien_1.jpg": {src: "images/territoire_iroquoien_1.jpg"},
"territoire_iroquoien_2.jpg": {src: "images/territoire_iroquoien_2.jpg", w: 1200, h: 960},
"iroquoiens_recoltes.jpg": {src: "images/iroquoiens_recoltes.jpg"},
"agriculture.jpg": {src: "images/agriculture.jpg", w: 1200, h: 800},
"territoire_algonquiens_2.jpg": {src: "images/territoire_algonquiens_2.jpg", w: 1200, h: 960},
"chasse_1.jpg": {src: "images/chasse_1.jpg", w: 1200, h: 800},
"peche_1.jpg": {src: "images/peche_1.jpg", w: 1200, h: 800},
"cueillette.jpg": {src: "images/cueillette.jpg", w: 1200, h: 800},
"vannerie.jpg": {src: "images/vannerie.jpg", w: 1200, h: 960},
"vetements.jpg": {src: "images/vetements.jpg", w: 1200, h: 800},
"poterie_b.jpg": {src: "images/poterie_b.jpg", w: 1200, h: 962},
"autochtones_troc.jpg": {src: "images/autochtones_troc.jpg", w: 1200, h: 801},
"ressources_troc.jpg": {src: "images/ressources_troc.jpg", w: 1200, h: 800},
"fabrication_canot.jpg": {src: "images/fabrication_canot.jpg"},
"construction_maison_longue.jpg": {src: "images/construction_maison_longue.jpg"},
"construction_palissade.jpg": {src: "images/construction_palissade.jpg"},
"fabrication_armes.jpg": {src: "images/fabrication_armes.jpg"},
"carte_territoires_physio.jpg": {src: "images/carte_territoires_physio.jpg"},
"village_iroquoien_ete.jpg": {src: "images/village_iroquoien_ete.jpg"},
"village_iroquoien_hiver.jpg": {src: "images/village_iroquoien_hiver.jpg"},
"territoire_iroquoiens_5.jpg": {src: "images/territoire_iroquoiens_5.jpg", w: 1200, h: 960},
"agriculture_2.jpg": {src: "images/agriculture_2.jpg", w: 1200, h: 960},
"autochtones_canot.jpg": {src: "images/autochtones_canot.jpg", w: 1200, h: 801},
"taches_hommes_2.jpg": {src: "images/taches_hommes_2.jpg", w: 1200, h: 960},
"transport_portage.jpg": {src: "images/transport_portage.jpg", w: 1200, h: 800},
"canot_ecorce.jpg": {src: "images/canot_ecorce.jpg", w: 1200, h: 800},
"raquettes.jpg": {src: "images/raquettes.jpg", w: 1200, h: 800},
"canot_2.jpg": {src: "images/canot_2.jpg", w: 1200, h: 960},
"transport_sentiers.jpg": {src: "images/transport_sentiers.jpg", w: 1200, h: 960},
"deplacement_raquettes_1.jpg": {src: "images/deplacement_raquettes_1.jpg", w: 1200, h: 960},
"sentiers_forestiers.jpg": {src: "images/sentiers_forestiers.jpg"},
"rivieres.jpg": {src: "images/rivieres.jpg"},
"mocassins.jpg": {src: "images/mocassins.jpg", w: 1200, h: 800},
"confection_vetements.jpg": {src: "images/confection_vetements.jpg"},
"poterie_argile.jpg": {src: "images/poterie_argile.jpg", w: 1200, h: 960},
"vannerie_ressources.jpg": {src: "images/vannerie_ressources.jpg", w: 1200, h: 960},
"algonquiens_patriarcat.jpg": {src: "images/algonquiens_patriarcat.jpg", w: 1200, h: 900},
"iroquoiens_matriarcat.jpg": {src: "images/iroquoiens_matriarcat.jpg", w: 1200, h: 900},
"iroquoiens_conseil_2.jpg": {src: "images/iroquoiens_conseil_2.jpg", w: 1200, h: 800},
"iroquoiens_conseil_femmes.jpg": {src: "images/iroquoiens_conseil_femmes.jpg", w: 1200, h: 960},
"iroquoiens_conseil.jpg": {src: "images/iroquoiens_conseil.jpg", w: 1200, h: 960},
"wigwam.jpg": {src: "images/wigwam.jpg"},
"iroquoien_maisons_longues.jpg": {src: "images/iroquoien_maisons_longues.jpg"},
"org_politique_matriarcat.jpg": {src: "images/org_politique_matriarcat.jpg", w: 1200, h: 800},
"org_politique_patriarcat.jpg": {src: "images/org_politique_patriarcat.jpg", w: 1200, h: 800}
}

const QUESTIONS = [
{
 id: "Q1",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le mode de vie des Iroquoiens vers 1500.",
 aspects: [{aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_iroquoiens.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les Iroquoiens ont un mode de vie sédentaire.",
 updatedAt: "2026-08-14T12:39:21.893Z"
},
{
 id: "Q2",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le mode de vie des Algonquiens vers 1500.",
 aspects: [{aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_algonquiens.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les Algonquiens ont un mode de vie nomade.",
 updatedAt: "2026-08-16T16:09:43.546Z"
},
{
 id: "Q3",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "Nomme deux activités pratiquées par les Iroquoiens pour se nourrir.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_iroquoiens.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "L'agriculture.\nLa chasse.\nLa cueillette.\nLa pêche.",
 updatedAt: "2026-08-14T12:41:17.126Z"
},
{
 id: "Q4",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 2",
 enonce: "Nomme deux activités pratiquées par les Algonquiens pour se nourrir.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_algonquiens.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La chasse.\nLa pêche.\nLa cueillette.",
 updatedAt: "2026-08-14T12:40:32.725Z"
},
{
 id: "Q5",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du territoire occupé par les Iroquoiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_iroquoien_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Relief : des plaines, notamment les Basses-terres du Saint-Laurent;\nClimat : des étés assez chauds et pluvieux et des hivers froids et enneigés;\nHydrographie : présence de nombreux cours d’eau, de lacs et du fleuve Saint-Laurent;\nRessources : des forêts, de la faune et des terres propices à l’agriculture.",
 updatedAt: "2026-08-14T12:50:29.765Z"
},
{
 id: "Q6",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du territoire occupé par les Algonquiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_algonquien_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Relief : un territoire généralement accidenté, avec des collines et des plateaux;\nClimat : des étés courts et des hivers longs et froids;\nHydrographie : présence de nombreux lacs et rivières;\nRessources : de vastes forêts ainsi qu'une faune et des ressources aquatiques abondantes.",
 updatedAt: "2026-08-14T12:50:10.143Z"
},
{
 id: "Q7",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du territoire occupé par les Iroquoiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_iroquoien_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Relief : des plaines, notamment les Basses-terres du Saint-Laurent;\nClimat : des étés assez chauds et pluvieux et des hivers froids et enneigés;\nHydrographie : présence de nombreux cours d’eau, de lacs et du fleuve Saint-Laurent;\nRessources : des forêts, de la faune et des terres propices à l’agriculture.",
 updatedAt: "2026-08-14T12:52:52.159Z"
},
{
 id: "Q8",
 niveau: 3,
 oi: "Caractériser un territoire",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Caractériser un territoire - 2",
 enonce: "Nomme deux caractéristiques du territoire occupé par les Algonquiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_algonquiens_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Relief : un territoire généralement accidenté, avec des collines et des plateaux;\nClimat : des étés courts et des hivers longs et froids;\nHydrographie : présence de nombreux lacs et rivières;\nRessources : de vastes forêts ainsi qu'une faune et des ressources aquatiques abondantes.",
 updatedAt: "2026-08-14T13:14:21.418Z"
},
{
 id: "Q9",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "À l'aide du document A, nomme deux aliments que les Iroquoiens cultivent pour se nourrir vers 1500.",
 aspects: [{aspect: "Activités économiques"}, {aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_recoltes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "Le maïs.\nLes haricots.\nLes courges.",
 updatedAt: "2026-08-14T21:11:16.497Z"
},
{
 id: "Q10",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "À l'aide du document A, nomme deux aliments que les Iroquoiens cultivent pour se nourrir.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "agriculture.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "Le maïs.\nLes haricots.\nLes courges.",
 updatedAt: "2026-08-14T13:13:34.646Z"
},
{
 id: "Q11",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les peuples autochtones.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "peche_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Ils pratiquent la pêche.",
 updatedAt: "2026-08-14T13:20:13.654Z"
},
{
 id: "Q12",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les peuples autochtones.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "cueillette.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Ils pratiquent la cueillette.",
 updatedAt: "2026-08-14T13:22:18.352Z"
},
{
 id: "Q13",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "agriculture.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Ils pratiquent l'agriculture.",
 updatedAt: "2026-08-14T13:22:50.346Z"
},
{
 id: "Q14",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vannerie.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La vannerie.",
 updatedAt: "2026-08-14T13:30:33.981Z"
},
{
 id: "Q15",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vetements.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La confection de vêtements.",
 updatedAt: "2026-08-14T13:27:25.331Z"
},
{
 id: "Q16",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Vie quotidienne"}, {aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_b.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La poterie.",
 updatedAt: "2026-08-14T13:30:14.285Z"
},
{
 id: "Q17",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme l’activité pratiquée par les peuples autochtones.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_troc.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le troc.",
 updatedAt: "2026-08-14T13:38:12.749Z"
},
{
 id: "Q18",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les peuples autochtones pratiquent le troc vers 1500.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_troc.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "ressources_troc.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les peuples autochtones pratiquent le troc pour obtenir des ressources ou des objets qu’ils ne possèdent pas ou qu’ils ne produisent pas eux-mêmes.",
 updatedAt: "2026-08-14T13:40:35.437Z"
},
{
 id: "Q19",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme la façon utilisée par les peuples autochtones pour échanger des ressources vers 1500.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_troc.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le troc.",
 updatedAt: "2026-08-14T13:42:34.805Z"
},
{
 id: "Q20",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent des activités pratiquées par les Algonquiens vers 1500. Associe chaque document à l’activité correspondante.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "chasse_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "peche_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "cueillette.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "autochtones_troc.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Chasse", "Cueillette", "Pêche", "Troc"]},
 guide: {type: "grille", entetes: ["Chasse", "Cueillette", "Pêche", "Troc"], rangees: [["A", "C", "B", "D"]]},
 updatedAt: "2026-08-14T14:09:24.535Z"
},
{
 id: "Q21",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent des activités pratiquées par les Iroquoiens vers 1500. Associe chaque document à l’activité correspondante.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "chasse_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "peche_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "cueillette.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "autochtones_troc.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Chasse", "Cueillette", "Pêche", "Troc"]},
 guide: {type: "grille", entetes: ["Chasse", "Cueillette", "Pêche", "Troc"], rangees: [["A", "C", "B", "D"]]},
 updatedAt: "2026-08-14T14:52:23.253Z"
},
{
 id: "Q22",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent des activités pratiquées par les Iroquoiens vers 1500. Associe chaque document à l’activité correspondante.",
 aspects: [{aspect: "Activités économiques"}, {aspect: "Vie quotidienne"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "agriculture.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "poterie_b.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "vannerie.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "agriculture.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Agriculture", "Confection de vêtements", "Poterie", "Vannerie"]},
 guide: {type: "grille", entetes: ["Agriculture", "Confection de vêtements", "Poterie", "Vannerie"], rangees: [["D", "A", "B", "C"]]},
 updatedAt: "2026-08-14T14:22:13.258Z"
},
{
 id: "Q23",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent des activités pratiquées par les Iroquoiens vers 1500. Associe chaque document à l’activité correspondante.",
 aspects: [{aspect: "Activités économiques"}, {aspect: "Vie quotidienne"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "fabrication_canot.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "construction_maison_longue.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "construction_palissade.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "fabrication_armes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Construction d'une maison longue", "Construction d'une palissade", "Fabrication d'armes", "Fabrication d'un canot d'écorce"]},
 guide: {type: "grille", entetes: ["Construction d'une maison longue", "Construction d'une palissade", "Fabrication d'armes", "Fabrication d'un canot d'écorce"], rangees: [["B", "C", "D", "A"]]},
 updatedAt: "2026-08-14T14:21:27.038Z"
},
{
 id: "Q24",
 niveau: 3,
 oi: "Établir des comparaisons",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Établir une différence",
 enonce: "Nomme une différence entre les activités économiques pratiquées par les Iroquoiens et les Algonquiens vers 1500.",
 aspects: [{aspect: "Activités économiques"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_algonquiens.jpg", soustitre: "Campement algonquien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "activites_economiques_iroquoiens.jpg", soustitre: "Village iroquoien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens pratiquent l’agriculture, tandis que les Algonquiens ne la pratiquent pas.",
 updatedAt: "2026-08-16T12:52:45.471Z"
},
{
 id: "Q25",
 niveau: 3,
 oi: "Situer dans l'espace",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Situer 1 élément dans l'espace",
 enonce: "Indique la lettre correspondant au territoire occupé par les Iroquoiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "carte_territoires_physio.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: false,
 guide: "B",
 updatedAt: "2026-08-14T14:58:38.208Z"
},
{
 id: "Q26",
 niveau: 3,
 oi: "Situer dans l'espace",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 1,
 soustag: "Situer 1 élément dans l'espace",
 enonce: "Indique la lettre correspondant au territoire occupé par les Algonquiens vers 1500.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "carte_territoires_physio.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: false,
 guide: "A",
 updatedAt: "2026-08-14T14:59:05.262Z"
},
{
 id: "Q27",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi le relief du territoire occupé par les Iroquoiens est un atout.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "agriculture_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "territoire_iroquoiens_5.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les plaines sont un atout parce qu’elles permettent aux Iroquoiens de pratiquer l’agriculture.",
 updatedAt: "2026-08-14T15:16:56.910Z"
},
{
 id: "Q28",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi le climat du territoire habité par les Iroquoiens est un atout.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_ete.jpg", soustitre: "Village iroquoien en été", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "village_iroquoien_hiver.jpg", soustitre: "Village iroquoien en hiver", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Le climat est un atout parce qu’en été, la température et la pluie permettent aux Iroquoiens de pratiquer l’agriculture.",
 updatedAt: "2026-08-14T15:42:40.883Z"
},
{
 id: "Q29",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi la faune du territoire occupé par les Iroquoiens est un atout.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "peche_1.jpg", soustitre: "Village iroquoien en été", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "chasse_1.jpg", soustitre: "Village iroquoien en hiver", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "La faune est un atout parce qu’elle fournit de la nourriture aux Iroquoiens.",
 updatedAt: "2026-08-14T15:25:08.421Z"
},
{
 id: "Q30",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi la forêt du territoire occupé par les Iroquoiens est un atout.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "fabrication_canot.jpg", soustitre: "Village iroquoien en été", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "construction_maison_longue.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "La forêt fournit des matériaux pour construire les maisons longues et les canots.",
 updatedAt: "2026-08-14T15:30:38.344Z"
},
{
 id: "Q31",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi le climat du territoire habité par les Iroquoiens est une contrainte.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "village_iroquoien_ete.jpg", soustitre: "Village iroquoien en été", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "village_iroquoien_hiver.jpg", soustitre: "Village iroquoien en hiver", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "e climat est une contrainte parce qu’en hiver, le froid et la neige limitent les activités et les déplacements.",
 updatedAt: "2026-08-14T15:43:16.874Z"
},
{
 id: "Q32",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les cours d’eau du territoire habité par les Iroquoiens sont un atout.",
 aspects: [{aspect: "Territoire"}, {aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_canot.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "territoire_iroquoiens_5.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les cours d’eau sont un atout parce qu’ils facilitent l’accès au territoire et les déplacements.",
 updatedAt: "2026-08-15T16:39:42.825Z"
},
{
 id: "Q33",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les rapides des cours d’eau du territoire habité par les Iroquoiens sont une contrainte.",
 aspects: [{aspect: "Territoire"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "autochtones_canot.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "transport_portage.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les rapides sont une contrainte parce qu’ils limitent les déplacements sur les cours d’eau.",
 updatedAt: "2026-08-14T15:47:02.719Z"
},
{
 id: "Q34",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme un moyen de transport utilisé par les Iroquoiens vers 1500 pour se déplacer sur les cours d’eau.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "canot_ecorce.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le canot.",
 updatedAt: "2026-08-14T17:51:09.636Z"
},
{
 id: "Q35",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme un moyen de transport utilisé par les Iroquoiens pour se déplacer en hiver.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "raquettes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La raquette.",
 updatedAt: "2026-08-14T18:27:51.016Z"
},
{
 id: "Q36",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme une voie de communication utilisée par les Iroquoiens.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "canot_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les cours d'eau.",
 updatedAt: "2026-08-14T21:10:35.763Z"
},
{
 id: "Q37",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme une voie de communication terrestre utilisée par les Iroquoiens.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "transport_sentiers.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les sentiers forestiers.",
 updatedAt: "2026-08-14T18:27:01.482Z"
},
{
 id: "Q38",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi le canot est utile aux Iroquoiens en été.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "territoire_iroquoiens_5.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "canot_2.jpg"}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Le canot est utile parce qu’il permet aux Iroquoiens de se déplacer sur les cours d’eau et d’accéder plus facilement aux différentes parties du territoire.",
 updatedAt: "2026-08-14T18:26:39.253Z"
},
{
 id: "Q39",
 niveau: 3,
 oi: "Établir des liens de causalité",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Explique pourquoi les raquettes sont utiles aux Iroquoiens en hiver.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "raquettes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "deplacement_raquettes_1.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "es raquettes sont utiles parce qu’elles facilitent les déplacements sur la neige lorsque les conditions hivernales rendent les déplacements plus difficiles.",
 updatedAt: "2026-08-14T18:09:15.189Z"
},
{
 id: "Q40",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 3",
 enonce: "Les documents A et B présentent des moyens de transport utilisés par les Iroquoiens vers 1500. Associe chaque document à l’élément correspondant.",
 aspects: [{aspect: "Territoire"}, {aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "raquettes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "canot_ecorce.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Canot", "Raquettes"]},
 guide: {type: "grille", entetes: ["Canot", "Raquettes"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-14T21:15:53.771Z"
},
{
 id: "Q41",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 2",
 enonce: "Les documents A et B présententdes voies de communication utilisés par les Iroquoiens vers 1500. Associe chaque document à l’élément correspondant.",
 aspects: [{aspect: "Transport"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "canot_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "transport_sentiers.jpg", source: "Reconstitution réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Cours d'eau", "Sentiers forestiers"]},
 guide: {type: "grille", entetes: ["Cours d'eau", "Sentiers forestiers"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-14T21:17:23.929Z"
},
{
 id: "Q42",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 4",
 enonce: "Les documents A à D présentent des moyens de transport et des voies de communication utilisés vers 1500. Associe chaque document à l’élément correspondant.",
 aspects: [{aspect: "Transport"}],
 documents: [
  {type: "textes", cols: [{titre: "Document A", ref: "raquettes.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document B", ref: "sentiers_forestiers.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document C", ref: "rivieres.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]},
  {type: "textes", cols: [{titre: "Document D", ref: "canot_ecorce.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}
 ],
 reponse: {type: "mettre-en-relation", elements: ["Moyens de transport", "Voies de communication"], double: true},
 guide: {type: "grille", entetes: ["Moyens de transport", "Voies de communication"], rangees: [["A et D", "B et C"]]},
 updatedAt: "2026-08-15T16:54:48.984Z"
},
{
 id: "Q43",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme un vêtement porté par les Iroquoiens pour se déplacer.",
 aspects: [{aspect: "Transport"}, {aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "mocassins.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Des mocassins.",
 updatedAt: "2026-08-15T16:46:10.909Z"
},
{
 id: "Q44",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l'aide du document A, nomme un matériau utilisé par les Iroquoiens pour fabriquer les vêtements.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "confection_vetements.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les peaux d'animaux.\nLes fourrures d'animaux.",
 updatedAt: "2026-08-15T18:59:58.349Z"
},
{
 id: "Q45",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l’aide du document A, nomme une forme d’art pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vannerie.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La vannerie.",
 updatedAt: "2026-08-15T17:31:59.727Z"
},
{
 id: "Q46",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l’aide du document A, nomme une forme d’art pratiquée par les Iroquoiens.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_b.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "La poterie.",
 updatedAt: "2026-08-15T17:35:52.553Z"
},
{
 id: "Q47",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 soustag: "Établir tous les faits - 2",
 enonce: "À l'aide des documents A et B, nomme deux formes d’art pratiquées par les Iroquoiens vers 1500.",
 aspects: [{aspect: "Culture"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vannerie.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "poterie_b.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 2},
 guide: "La poterie et la vannerie.",
 updatedAt: "2026-08-15T18:58:18.118Z"
},
{
 id: "Q48",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l’aide du document A, nomme un matériau utilisé par les Iroquoiens pour la vannerie.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "vannerie_ressources.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Des fibres végétales ou des tiges végétales.",
 updatedAt: "2026-08-15T19:07:24.686Z"
},
{
 id: "Q49",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "À l’aide du document A, nomme un matériau utilisé par les Iroquoiens pour la poterie.",
 aspects: [{aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_argile.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "L'argile.",
 updatedAt: "2026-08-15T19:07:44.310Z"
},
{
 id: "Q50",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 2,
 enonce: "Les documents A et B présentent deux formes d’art pratiquées par les Iroquoiens vers 1500. Associe chaque document à la forme d’art correspondante.",
 aspects: [{aspect: "Culture"}, {aspect: "Vie quotidienne"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "poterie_argile.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "vannerie_ressources.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Poterie", "Vannerie"]},
 guide: {type: "grille", entetes: ["Poterie", "Vannerie"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-15T19:09:32.005Z"
},
{
 id: "Q51",
 niveau: 3,
 oi: "Établir des comparaisons",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Établir une différence",
 enonce: "Nomme une différence entre les habitations des Iroquoiens et des Algonquiens vers 1500.",
 aspects: [{aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_algonquiens.jpg", soustitre: "Campement algonquien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "activites_economiques_iroquoiens.jpg", soustitre: "Village iroquoien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens habitent dans des maisons longues, tandis que les Algonquiens habitent dans des wigwams.",
 updatedAt: "2026-08-16T12:55:42.857Z"
},
{
 id: "Q52",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Les documents A et B présentent la structure politique des sociétés iroquoienne et algonquienne vers 1500. Associe chaque document à la société correspondante.",
 aspects: [{aspect: "Gouvernement"}, {aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_patriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "iroquoiens_matriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Société algonquienne", "Société iroquoienne"]},
 guide: {type: "grille", entetes: ["Société algonquienne", "Société iroquoienne"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-16T17:04:28.410Z"
},
{
 id: "Q53",
 niveau: 3,
 oi: "Établir des comparaisons",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Établir une différence",
 enonce: "Nomme une différence entre la structure politique des Iroquoiens et celle des Algonquiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}, {aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_patriarcat.jpg", soustitre: "La structure politique des Algonquiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "iroquoiens_matriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens ont une structure matriarcale, tandis que les Algonquiens ont une structure patriarcale.",
 updatedAt: "2026-08-16T12:53:41.981Z"
},
{
 id: "Q54",
 niveau: 3,
 oi: "Établir des comparaisons",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Établir une différence",
 enonce: "Nomme une différence entre le mode de vie des Iroquoiens et des Algonquiens vers 1500.",
 aspects: [{aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "activites_economiques_algonquiens.jpg", soustitre: "Campement algonquien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "activites_economiques_iroquoiens.jpg", soustitre: "Village iroquoien", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 3},
 guide: "Les Iroquoiens ont un mode de vie sédentaire, tandis que les Algonquiens ont un mode de vie nomade.",
 updatedAt: "2026-08-16T12:56:25.794Z"
},
{
 id: "Q55",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le groupe de personnes qui désigne les chefs chez les Iroquoiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_conseil_2.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Les aînées.\nLes femmes âgées.",
 updatedAt: "2026-08-16T16:32:51.290Z"
},
{
 id: "Q56",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le rôle politique des aînées chez les Iroquoiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_conseil_femmes.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Elles désignent les chefs.",
 updatedAt: "2026-08-16T16:38:13.933Z"
},
{
 id: "Q57",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la structure politique chez les Iroquoiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "org_politique_matriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le matriarcat.",
 updatedAt: "2026-08-16T17:05:58.278Z"
},
{
 id: "Q58",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la structure politique chez les Algonquiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "algonquiens_patriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le patriarcat.",
 updatedAt: "2026-08-16T16:37:32.359Z"
},
{
 id: "Q59",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme le moyen par lequel les Iroquoiens prennent les décisions importantes vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_conseil.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "En conseil.",
 updatedAt: "2026-08-16T16:39:39.105Z"
},
{
 id: "Q60",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 soustag: "Mettre en relation des faits - 2",
 enonce: "Les documents A et B présentent les habitations des Iroquoiens et des Algonquiens vers 1500. Associe chaque document à la société correspondante.",
 aspects: [{aspect: "Population"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "wigwam.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "iroquoien_maisons_longues.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Algonquiens", "Iroquoiens"]},
 guide: {type: "grille", entetes: ["Algonquiens", "Iroquoiens"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-16T16:43:30.313Z"
},
{
 id: "Q61",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Les documents A et B présentent la structure politique des sociétés iroquoienne et algonquienne vers 1500. Associe chaque document à l'organisation politique correspondante.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_matriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "algonquiens_patriarcat.jpg", soustitre: "La structure politique des Algonquiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Matriarcat", "Patriarcat"]},
 guide: {type: "grille", entetes: ["Matriarcat", "Patriarcat"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-16T17:08:37.282Z"
},
{
 id: "Q62",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Les documents A et B présentent la structure politique des sociétés iroquoienne et algonquienne vers 1500. Associe chaque document à la société correspondante.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "org_politique_patriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "org_politique_matriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Société algonquienne", "Société iroquoienne"]},
 guide: {type: "grille", entetes: ["Société algonquienne", "Société iroquoienne"], rangees: [["A", "B"]]},
 updatedAt: "2026-08-16T17:09:57.486Z"
},
{
 id: "Q63",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la structure politique chez les Algonquiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "org_politique_patriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le patriarcat.",
 updatedAt: "2026-08-16T17:05:38.971Z"
},
{
 id: "Q64",
 niveau: 3,
 oi: "Établir des faits",
 competence: "Lire l'organisation du territoire",
 periodes: ["Les Iroquoiens vers 1500"],
 points: 1,
 soustag: "Établir 1 fait - 1",
 enonce: "Nomme la structure politique chez les Iroquoiens vers 1500.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "iroquoiens_matriarcat.jpg", soustitre: "La structure politique des Iroquoiens", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "lignes", nombre: 1},
 guide: "Le matriarcat.",
 updatedAt: "2026-08-16T17:06:15.803Z"
},
{
 id: "Q65",
 niveau: 3,
 oi: "Mettre en relation des faits",
 competence: "S'ouvrir à la diversité",
 periodes: ["Les Iroquoiens vers 1500", "Les Algonquiens vers 1500"],
 points: 2,
 enonce: "Les documents A et B présentent la structure politique des sociétés iroquoienne et algonquienne vers 1500. Associe chaque document à l'organisation politique correspondante.",
 aspects: [{aspect: "Gouvernement"}],
 documents: [{type: "textes", cols: [{titre: "Document A", ref: "org_politique_patriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}, {type: "textes", cols: [{titre: "Document B", ref: "org_politique_matriarcat.jpg", source: "Reconstitution historique réalisée à l'aide de l'intelligence artificielle (ChatGPT, OpenAI), 2026."}]}],
 reponse: {type: "mettre-en-relation", elements: ["Matriarcat", "Patriarcat"]},
 guide: {type: "grille", entetes: ["Matriarcat", "Patriarcat"], rangees: [["B", "A"]]},
 updatedAt: "2026-08-16T17:09:32.988Z"
}
]
